theme: jekyll-theme-minimal

title: "Jaichung Lee"
description: "PhD Student, University of Oregon"
# theme: minima

nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research
  - title: "Teaching"
    url: /teaching
  - title: "CV"
    url: /cv
  # - title: "Contact"
  #   url: /contact
